# Use root/example as user/password credentials
version: '3.7'

services:
  webserver:
    image: phpstorm/php-apache:8.3
    restart: always
    ports:
      - "8189:80"
    volumes:
      - ./:/var/www/html
      - ./dist/php.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  memcached:
    image: memcached:latest
    restart: always
    ports:
      - "12222:11211"

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
