controllers:
  resource:
    path: ../../src/Controller/
    namespace: Eurosat7\ExampleHttpEventStream\Controller
  type: attribute

kernel:
  resource: Eurosat7\ExampleHttpEventStream\Kernel
  type: attribute