services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Eurosat7\ExampleHttpEventStream\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  Eurosat7\ExampleHttpEventStream\Event\MinificationSubscriber:
    tags:
      - { name: kernel.event_subscriber }
